name: Unmesh Jagtap
description: Technology | Leadership | Strategy
avatar: https://raw.githubusercontent.com/uaj3/unmeshjagtap.github.io/master/images/unmesh.jpeg

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Unmesh Jagtap"
resume_title:                   "About"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "unmesh1.jagtap1@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "307-4587"
resume_contact_address:         "San Mateo"

resume_header_contact_info:     ""
display_header_contact_info:    "false"

resume_header_intro: "
<p> 
Unmesh is a Director of Engineering at Twitter where he is responsible for storage, publish subscribe and real time stream processing systems that store and process mission critical data for Twitter. Before Twitter, he was at Oracle working in the Parallel Execution group where he made contributions to the database optimizer and parallel execution engine. 
</p>
<p>
Unmesh holds a Masters degree in Computer Science from Cornell University and is currently pursuing an Executive MBA from the Wharton School.
</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_license_certifications:   true
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/uaj3"
  resume_twitter_url:           "http://twitter.com/JagtapUnmesh"
  resume_linkedin_url:          "https://www.linkedin.com/in/unmesh-jagtap-1b295011"
  resume_website_url:           "http://unmeshjagtap.com"
 #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      false

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

footer-links:
  email: unmesh1.jagtap1@gmail.com
  github: uaj3
  linkedin: unmesh-jagtap-1b295011
  rss: # just type anything here for a working RSS iconz
  twitter: JagtapUnmesh

disqus:
google_analytics:
url:
baseurl: ""

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME